### ISSUE TITLE
Chrome DevTool Warning with inherited behavior

### ISSUE THREAD

**Issue by GeoloeG-IsT** [PolymerElements/iron-form-element-behavior#22] opened 2015-11-17 23:03 UTC
I have [one component](https://github.com/MeTaNoV/gold-password-input/blob/master/gold-password-input.html) which inherits `Polymer.IronFormElementBehavior`

When I open the document page with `polyserve`, I have some warnings, and some more warnings when I try to click on an element of the behavior section like in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/11166016/11227636/694d332e-8d87-11e5-81a2-098381776731.png)

**Comment by notwaldorf** [comment] 2015-11-18 22:09
I think that only works when you serve the whole elements catalog, because you're not serving the other docs pages, so you can't navigate to them. I don't know what `docs.js` and why you're not getting the other imports -- my guess is you're not doing an html import for those files.

**Comment by GeoloeG-IsT** [comment] 2015-11-18 22:18
This is my [code](https://github.com/MeTaNoV/gold-password-input/blob/master/gold-password-input.html). I do the proper behavior import there. I don't know however the magic that happens in `<iron-component-pages>` that generate this content automatically. Where should I do those import to work as expected?

**Comment by notwaldorf** [comment] 2015-11-18 22:24
/cc @blasten since I think this is maybe form recent changes to the catalog. For what it's worth, if I serve the `paper-radio-group` docs page, I also get angry warnings:
<img width="1053" alt="screen shot 2015-11-18 at 2 23 52 pm" src="https://cloud.githubusercontent.com/assets/1369170/11256305/0673823e-8e00-11e5-97ef-4a7d9d3d0c4d.png">

It might just be that serving individual docs pages is not super supported right now :(

**Comment by GeoloeG-IsT** [comment] 2015-11-18 22:34
might be the case... I just try to ship my first polished element, and the overall process is not yet stable! :) I would like for example to generate the README.md automatically, but only tedium is currently supporting this at the google elements level! :smile: Well, you have some priority I suppose!

BTW, I raised a more concerning issue regarding [`<iron-input>`](https://github.com/PolymerElements/iron-input/issues/60) and PR'ed it. Could you PTAL or cc someone responsible for this component? :smile_cat: 

Thanks a lot!

**Comment by notwaldorf** [comment] 2015-11-18 22:53
Be gentle to `tedium` -- it's a tool that's a week old, and has only been used by our team in this week. You can open an issue with it so that you can configure the path to your repo, or you can temporarily fork it and run it yourself. Up until last week, we were modifying the README.md files manually, so I can assure you the process is stable enough. 

Secondly, I think in its current state, `iron-component-page` is an element that has predominantly been enhanced to work with the elements catalog, which is the main documentation source for the Polymer elements. It is true that it can show your docs as well, but given that your docs won't live in our elements catalog, you can't expect all the outgoing links to work, unfortunately. You can also open a bug with `iron-component-page` if you want to track this further.

I'm just objecting to the overall process being stable bit :)

In any case, closing this as it's not a bug about this element at all. I've cc'ed myself on your iron-input, and I'll take a look at it when I have a chance.

**Closed as completed by notwaldorf** 2015-11-18 22:53 UTC
Labels: pending-response

**Comment by GeoloeG-IsT** [comment] 2015-11-18 23:00
The overall google element process is indeed (hopefully) stable! :) Just take into account that people are also developing some elements and are confronted to the same needs which are currently not 100% fulfilled by your tools at our level. I am sure it is just a question of time, I'll be patient.
I'll file an issue on the `<iron-component-page>`! 
Thanks again!
